//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audio.Information
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Audio.Information.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом.
        /// </summary>
        internal static string Album_ru
        {
            get
            {
                return ResourceManager.GetString("Album.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость потока.
        /// </summary>
        internal static string AudioBitrate_ru
        {
            get
            {
                return ResourceManager.GetString("AudioBitrate.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество каналов.
        /// </summary>
        internal static string AudioChannels_ru
        {
            get
            {
                return ResourceManager.GetString("AudioChannels.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота дискретизации.
        /// </summary>
        internal static string AudioSampleRate_ru
        {
            get
            {
                return ResourceManager.GetString("AudioSampleRate.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодек.
        /// </summary>
        internal static string Codec_ru
        {
            get
            {
                return ResourceManager.GetString("Codec.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string Duration_ru
        {
            get
            {
                return ResourceManager.GetString("Duration.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        internal static string Genre_ru
        {
            get
            {
                return ResourceManager.GetString("Genre.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        internal static string Location_ru
        {
            get
            {
                return ResourceManager.GetString("Location.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        internal static string Performer_ru
        {
            get
            {
                return ResourceManager.GetString("Performer.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string Title_ru
        {
            get
            {
                return ResourceManager.GetString("Title.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер дорожки.
        /// </summary>
        internal static string Track_ru
        {
            get
            {
                return ResourceManager.GetString("Track.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        internal static string Year_ru
        {
            get
            {
                return ResourceManager.GetString("Year.ru", resourceCulture);
            }
        }
    }
}
