//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCollection
{
    using System;
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en()
        {
        }
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeCollection.Strings.en", typeof(Strings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на All &apos;{0}&apos;.
        /// </summary>
        internal static string AllObjects
        {
            get
            {
                return ResourceManager.GetString("AllObjects", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Any class&gt;.
        /// </summary>
        internal static string AnyClass
        {
            get
            {
                return ResourceManager.GetString("AnyClass", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Any attribute&gt;.
        /// </summary>
        internal static string AnyField
        {
            get
            {
                return ResourceManager.GetString("AnyField", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup.
        /// </summary>
        internal static string Backup
        {
            get
            {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base template.
        /// </summary>
        internal static string BaseTemplate
        {
            get
            {
                return ResourceManager.GetString("BaseTemplate", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import data.
        /// </summary>
        internal static string ButtonPlugin
        {
            get
            {
                return ResourceManager.GetString("ButtonPlugin", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common.
        /// </summary>
        internal static string CategoryDefault
        {
            get
            {
                return ResourceManager.GetString("CategoryDefault", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removal of a template will lead to removal of templates which depend on the deleted. Also the data based on a deleted template will be lost. You really want to remove a template?.
        /// </summary>
        internal static string ConfirmDeleteClass
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteClass", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removal of attribute will lead data to loss. You really want to remove attribute?.
        /// </summary>
        internal static string ConfirmDeleteField
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteField", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на You really want to remove the filter &apos;{ 0 }&apos;?.
        /// </summary>
        internal static string ConfirmDeleteFilter
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на You really want to remove the folder &apos;{ 0 }&apos;?.
        /// </summary>
        internal static string ConfirmDeleteFolder
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removal of record can lead to loss of data which refer to this record. You really want to remove record?.
        /// </summary>
        internal static string ConfirmDeleteRecord
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteRecord", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright.
        /// </summary>
        internal static string Copyright
        {
            get
            {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data are backuped.
        /// </summary>
        internal static string DataBackuped
        {
            get
            {
                return ResourceManager.GetString("DataBackuped", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на The database should be cleared before an import of data will be carried out..
        /// </summary>
        internal static string DataClear
        {
            get
            {
                return ResourceManager.GetString("DataClear", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when opening a file {0}..
        /// </summary>
        internal static string ErrorOpen
        {
            get
            {
                return ResourceManager.GetString("ErrorOpen", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string Filters
        {
            get
            {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        internal static string Folder
        {
            get
            {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        internal static string Import
        {
            get
            {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на The records import.
        /// </summary>
        internal static string ImportData
        {
            get
            {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not show this message again..
        /// </summary>
        internal static string LangChangedCheck
        {
            get
            {
                return ResourceManager.GetString("LangChangedCheck", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на The language for this application has been changed. The change will take effect the next time the application is started..
        /// </summary>
        internal static string LangChangedContent
        {
            get
            {
                return ResourceManager.GetString("LangChangedContent", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language changed.
        /// </summary>
        internal static string LangChangedTitle
        {
            get
            {
                return ResourceManager.GetString("LangChangedTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is necessary to choose at least one template which objects will contain in the folder..
        /// </summary>
        internal static string NotSelectedClassInFolder
        {
            get
            {
                return ResourceManager.GetString("NotSelectedClassInFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string Open
        {
            get
            {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is necessary to conduct a file name..
        /// </summary>
        internal static string ReguiredFileName
        {
            get
            {
                return ResourceManager.GetString("ReguiredFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template.
        /// </summary>
        internal static string Template
        {
            get
            {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates of elements of a collection.
        /// </summary>
        internal static string TemplateCollection
        {
            get
            {
                return ResourceManager.GetString("TemplateCollection", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на The template (or attributes of a template) refers to an absent template and be imported can&apos;t..
        /// </summary>
        internal static string TemplateNotExist
        {
            get
            {
                return ResourceManager.GetString("TemplateNotExist", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today:.
        /// </summary>
        internal static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name of the folder should be unique..
        /// </summary>
        internal static string UniqueNameFolder
        {
            get
            {
                return ResourceManager.GetString("UniqueNameFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is necessary to specify the folder name..
        /// </summary>
        internal static string UnknownNameFolder
        {
            get
            {
                return ResourceManager.GetString("UnknownNameFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL.
        /// </summary>
        internal static string URL
        {
            get
            {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-page.
        /// </summary>
        internal static string WebPage
        {
            get
            {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на (No).
        /// </summary>
        internal static string WithoutFilter
        {
            get
            {
                return ResourceManager.GetString("WithoutFilter", resourceCulture);
            }
        }
    }
}
