//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCollection
{
    using System;
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeCollection.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все &apos;{0}&apos;.
        /// </summary>
        internal static string AllObjects
        {
            get
            {
                return ResourceManager.GetString("AllObjects", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Любой класс&gt;.
        /// </summary>
        internal static string AnyClass
        {
            get
            {
                return ResourceManager.GetString("AnyClass", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Любое поле&gt;.
        /// </summary>
        internal static string AnyField
        {
            get
            {
                return ResourceManager.GetString("AnyField", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение.
        /// </summary>
        internal static string Backup
        {
            get
            {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовый шаблон.
        /// </summary>
        internal static string BaseTemplate
        {
            get
            {
                return ResourceManager.GetString("BaseTemplate", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить данные.
        /// </summary>
        internal static string ButtonPlugin
        {
            get
            {
                return ResourceManager.GetString("ButtonPlugin", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее.
        /// </summary>
        internal static string CategoryDefault
        {
            get
            {
                return ResourceManager.GetString("CategoryDefault", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление шаблона приведет к удалению шаблонов, которые зависят от удаляемого. Также будут потеряны данные, основанные на удаляемом шаблоне. Вы действительно хотите удалить шаблон?.
        /// </summary>
        internal static string ConfirmDeleteClass
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteClass", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление атрибута приведет к потере данные. Вы действительно хотите удалить атрибут?.
        /// </summary>
        internal static string ConfirmDeleteField
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteField", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить фильтр &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteFilter
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить папку &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteFolder
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление записи может привести к потере данных, которые ссылаются на данную запись. Вы действительно хотите удалить запись?.
        /// </summary>
        internal static string ConfirmDeleteRecord
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteRecord", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright.
        /// </summary>
        internal static string Copyright
        {
            get
            {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на CurrentSchema.xml.
        /// </summary>
        internal static string CurrentSchema
        {
            get
            {
                return ResourceManager.GetString("CurrentSchema", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные сохранены.
        /// </summary>
        internal static string DataBackuped
        {
            get
            {
                return ResourceManager.GetString("DataBackuped", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных должна быть очищена прежде, чем будет осуществлен импорт данных..
        /// </summary>
        internal static string DataClear
        {
            get
            {
                return ResourceManager.GetString("DataClear", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на DefaultSchema.xml.
        /// </summary>
        internal static string DefaultSchema
        {
            get
            {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при открытии файла {0}..
        /// </summary>
        internal static string ErrorOpen
        {
            get
            {
                return ResourceManager.GetString("ErrorOpen", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтры.
        /// </summary>
        internal static string Filters
        {
            get
            {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка.
        /// </summary>
        internal static string Folder
        {
            get
            {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home collection.
        /// </summary>
        internal static string HomeCollection
        {
            get
            {
                return ResourceManager.GetString("HomeCollection", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт.
        /// </summary>
        internal static string Import
        {
            get
            {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт данных.
        /// </summary>
        internal static string ImportData
        {
            get
            {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не показывать больше это сообщение..
        /// </summary>
        internal static string LangChangedCheck
        {
            get
            {
                return ResourceManager.GetString("LangChangedCheck", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык интерфейса приложения изменен. Это изменение вступит в силу при следующем запуске приложения..
        /// </summary>
        internal static string LangChangedContent
        {
            get
            {
                return ResourceManager.GetString("LangChangedContent", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменен язык приложения.
        /// </summary>
        internal static string LangChangedTitle
        {
            get
            {
                return ResourceManager.GetString("LangChangedTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать хотя бы один шаблон, объекты которого будут содержаться в папке..
        /// </summary>
        internal static string NotSelectedClassInFolder
        {
            get
            {
                return ResourceManager.GetString("NotSelectedClassInFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string Open
        {
            get
            {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо вести имя файла..
        /// </summary>
        internal static string ReguiredFileName
        {
            get
            {
                return ResourceManager.GetString("ReguiredFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон.
        /// </summary>
        internal static string Template
        {
            get
            {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблоны элементов коллекции.
        /// </summary>
        internal static string TemplateCollection
        {
            get
            {
                return ResourceManager.GetString("TemplateCollection", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон (или атрибуты шаблона) ссылается на отсутствующий шаблон и импортирован быть не может..
        /// </summary>
        internal static string TemplateNotExist
        {
            get
            {
                return ResourceManager.GetString("TemplateNotExist", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня:.
        /// </summary>
        internal static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование папки должно быть уникальным..
        /// </summary>
        internal static string UniqueNameFolder
        {
            get
            {
                return ResourceManager.GetString("UniqueNameFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать наименование папки..
        /// </summary>
        internal static string UnknownNameFolder
        {
            get
            {
                return ResourceManager.GetString("UnknownNameFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL.
        /// </summary>
        internal static string URL
        {
            get
            {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-страница.
        /// </summary>
        internal static string WebPage
        {
            get
            {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Нет).
        /// </summary>
        internal static string WithoutFilter
        {
            get
            {
                return ResourceManager.GetString("WithoutFilter", resourceCulture);
            }
        }
    }
}
