//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.Information
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File.Information.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessed.
        /// </summary>
        internal static string Accessed_en
        {
            get
            {
                return ResourceManager.GetString("Accessed.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ.
        /// </summary>
        internal static string Accessed_ru
        {
            get
            {
                return ResourceManager.GetString("Accessed.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to file is denied..
        /// </summary>
        internal static string AccessError_en
        {
            get
            {
                return ResourceManager.GetString("AccessError.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к файлу запрещен..
        /// </summary>
        internal static string AccessError_ru
        {
            get
            {
                return ResourceManager.GetString("AccessError.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created_en
        {
            get
            {
                return ResourceManager.GetString("Created.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        internal static string Created_ru
        {
            get
            {
                return ResourceManager.GetString("Created.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_en
        {
            get
            {
                return ResourceManager.GetString("Error.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error_ru
        {
            get
            {
                return ResourceManager.GetString("Error.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - is folder. File name required..
        /// </summary>
        internal static string FileIsNotFolder_en
        {
            get
            {
                return ResourceManager.GetString("FileIsNotFolder.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - это папка. Необходимо указать файл..
        /// </summary>
        internal static string FileIsNotFolder_ru
        {
            get
            {
                return ResourceManager.GetString("FileIsNotFolder.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is empty, contains only white spaces, or contains invalid characters..
        /// </summary>
        internal static string FileNameRequired_en
        {
            get
            {
                return ResourceManager.GetString("FileNameRequired.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя файла..
        /// </summary>
        internal static string FileNameRequired_ru
        {
            get
            {
                return ResourceManager.GetString("FileNameRequired.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string FileType_en
        {
            get
            {
                return ResourceManager.GetString("FileType.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип файла.
        /// </summary>
        internal static string FileType_ru
        {
            get
            {
                return ResourceManager.GetString("FileType.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder_en
        {
            get
            {
                return ResourceManager.GetString("Folder.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        internal static string Folder_ru
        {
            get
            {
                return ResourceManager.GetString("Folder.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden_en
        {
            get
            {
                return ResourceManager.GetString("Hidden.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрытый.
        /// </summary>
        internal static string Hidden_ru
        {
            get
            {
                return ResourceManager.GetString("Hidden.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name..
        /// </summary>
        internal static string InvalidFileName_en
        {
            get
            {
                return ResourceManager.GetString("InvalidFileName.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное имя файла..
        /// </summary>
        internal static string InvalidFileName_ru
        {
            get
            {
                return ResourceManager.GetString("InvalidFileName.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location_en
        {
            get
            {
                return ResourceManager.GetString("Location.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        internal static string Location_ru
        {
            get
            {
                return ResourceManager.GetString("Location.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Modified_en
        {
            get
            {
                return ResourceManager.GetString("Modified.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменён.
        /// </summary>
        internal static string Modified_ru
        {
            get
            {
                return ResourceManager.GetString("Modified.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_en
        {
            get
            {
                return ResourceManager.GetString("Name.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string Name_ru
        {
            get
            {
                return ResourceManager.GetString("Name.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths must be less than 248 characters, and file names must be less than 260 characters..
        /// </summary>
        internal static string PathTooLong_en
        {
            get
            {
                return ResourceManager.GetString("PathTooLong.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное имя файла. Оно не должно превышать 260 символов..
        /// </summary>
        internal static string PathTooLong_ru
        {
            get
            {
                return ResourceManager.GetString("PathTooLong.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        internal static string ReadOnly_en
        {
            get
            {
                return ResourceManager.GetString("ReadOnly.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только для чтения.
        /// </summary>
        internal static string ReadOnly_ru
        {
            get
            {
                return ResourceManager.GetString("ReadOnly.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission..
        /// </summary>
        internal static string SecurityError_en
        {
            get
            {
                return ResourceManager.GetString("SecurityError.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав доступа..
        /// </summary>
        internal static string SecurityError_ru
        {
            get
            {
                return ResourceManager.GetString("SecurityError.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size_en
        {
            get
            {
                return ResourceManager.GetString("Size.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string Size_ru
        {
            get
            {
                return ResourceManager.GetString("Size.ru", resourceCulture);
            }
        }
    }
}
