//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCollection.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeCollection.Properties.Strings.en", typeof(Strings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSize.
        /// </summary>
        internal static string AutoSize
        {
            get
            {
                return ResourceManager.GetString("AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the auto size mode for this column..
        /// </summary>
        internal static string AutoSizeDesc
        {
            get
            {
                return ResourceManager.GetString("AutoSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior
        {
            get
            {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds value.
        /// </summary>
        internal static string Bounds
        {
            get
            {
                return ResourceManager.GetString("Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column
        {
            get
            {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns
        {
            get
            {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание объектов.
        /// </summary>
        internal static string CreatingObjects
        {
            get
            {
                return ResourceManager.GetString("CreatingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal places.
        /// </summary>
        internal static string Decimal
        {
            get
            {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DefaultValue
        {
            get
            {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider width.
        /// </summary>
        internal static string DividerWidth
        {
            get
            {
                return ResourceManager.GetString("DividerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the column divider in pixels..
        /// </summary>
        internal static string DividerWidthDesc
        {
            get
            {
                return ResourceManager.GetString("DividerWidthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated.
        /// </summary>
        internal static string Evaluated
        {
            get
            {
                return ResourceManager.GetString("Evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string Expression
        {
            get
            {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill weight.
        /// </summary>
        internal static string FillWeight
        {
            get
            {
                return ResourceManager.GetString("FillWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight that is used when sizing this column in the &apos;yes&apos; suto size mode..
        /// </summary>
        internal static string FillWeightDesc
        {
            get
            {
                return ResourceManager.GetString("FillWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form
        {
            get
            {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format
        {
            get
            {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Form...).
        /// </summary>
        internal static string FormEdit
        {
            get
            {
                return ResourceManager.GetString("FormEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        internal static string Frozen
        {
            get
            {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether a column will move ehrn a user scrolls..
        /// </summary>
        internal static string FrozenDesc
        {
            get
            {
                return ResourceManager.GetString("FrozenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General
        {
            get
            {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group
        {
            get
            {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        internal static string Increment
        {
            get
            {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите значение.
        /// </summary>
        internal static string InputValue
        {
            get
            {
                return ResourceManager.GetString("InputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (List...).
        /// </summary>
        internal static string List
        {
            get
            {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum
        {
            get
            {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum
        {
            get
            {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width.
        /// </summary>
        internal static string MinimumWidth
        {
            get
            {
                return ResourceManager.GetString("MinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum width pf the column in pixels..
        /// </summary>
        internal static string MinimumWidthDesc
        {
            get
            {
                return ResourceManager.GetString("MinimumWidthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caption text on the column&apos;s header cell..
        /// </summary>
        internal static string NameDesc
        {
            get
            {
                return ResourceManager.GetString("NameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        internal static string Plugin
        {
            get
            {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix
        {
            get
            {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference
        {
            get
            {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizable.
        /// </summary>
        internal static string Resizable
        {
            get
            {
                return ResourceManager.GetString("Resizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the column is resizable..
        /// </summary>
        internal static string ResizableDesc
        {
            get
            {
                return ResourceManager.GetString("ResizableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix
        {
            get
            {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands separator.
        /// </summary>
        internal static string Thousands
        {
            get
            {
                return ResourceManager.GetString("Thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time
        {
            get
            {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя колонки должно быть уникально..
        /// </summary>
        internal static string UniqueColumnName
        {
            get
            {
                return ResourceManager.GetString("UniqueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string UrlType
        {
            get
            {
                return ResourceManager.GetString("UrlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value
        {
            get
            {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Values
        {
            get
            {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View
        {
            get
            {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Visible
        {
            get
            {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the column is visible..
        /// </summary>
        internal static string VisibleDesc
        {
            get
            {
                return ResourceManager.GetString("VisibleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width
        {
            get
            {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current width of the column..
        /// </summary>
        internal static string WidthDesc
        {
            get
            {
                return ResourceManager.GetString("WidthDesc", resourceCulture);
            }
        }
    }
}
